In [74]:
import pandas as pd

In [75]:
file_name = "Day11_Messy_Company_Employee_Dataset.csv"
employee_data = pd.read_csv(file_name)
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [76]:
print("========== COMPANY EMPLOYEE DATASET ==========")
display(employee_data.head())

========== COMPANY EMPLOYEE DATASET ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [77]:
print("========== DATASET SHAPE ==========")
print(f"Number of rows: {employee_data.shape[0]}")
print(f"Number of columns: {employee_data.shape[1]}")
print(f"Dataset shape: {employee_data.shape}")

========== DATASET SHAPE ==========
Number of rows: 157
Number of columns: 12
Dataset shape: (157, 12)

In [78]:
print("========== COLUMN NAMES ==========")
for column_name in employee_data.columns:
  print("-", column_name)

========== COLUMN NAMES ==========
- Employee_ID
- Employee_Name
- Department
- Job_Title
- Age
- Gender
- Annual_Salary
- Experience_Years
- Joining_Date
- City
- Performance_Score
- Work_Mode

In [79]:
print("========== DATA TYPES ==========")
print(employee_data.dtypes)

========== DATA TYPES ==========
Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [80]:
print("========== DATASET INFROMATION ==========")
employee_data.info()

========== DATASET INFROMATION ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [81]:
print("========== DESCRIPTIVE STATISTICS ==========")
display(employee_data.describe())

========== DESCRIPTIVE STATISTICS ==========

              Age  Annual_Salary  Experience_Years  Performance_Score
count  153.000000     152.000000        154.000000         154.000000
mean    38.130719   89240.592105          8.990909           3.525974
std      9.361661   22626.172309          4.983874           0.930233
min     21.000000   43331.000000          0.600000           2.000000
25%     30.000000   71198.500000          4.450000           3.000000
50%     39.000000   90046.500000          9.350000           4.000000
75%     46.000000  107328.000000         13.200000           4.000000
max     52.000000  162942.000000         17.400000           5.000000

In [82]:
print("========== MISSING VALUES ==========")
missing_values = employee_data.isnull().sum()
display(missing_values)

========== MISSING VALUES ==========

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [83]:
print("========== MISSING VALUE PERCENTAGE ==========")
missing_percentage = (
    employee_data.isnull().mean() * 100
).round(2)

missing_summary = pd.DataFrame(
    {
        "Missing_Count": missing_values,
        "Missing_Percentage": missing_percentage
    }
)

display(missing_summary)

========== MISSING VALUE PERCENTAGE ==========

                   Missing_Count  Missing_Percentage
Employee_ID                    0                0.00
Employee_Name                  0                0.00
Department                     5                3.18
Job_Title                      0                0.00
Age                            4                2.55
Gender                         5                3.18
Annual_Salary                  5                3.18
Experience_Years               3                1.91
Joining_Date                   0                0.00
City                           5                3.18
Performance_Score              3                1.91
Work_Mode                      2                1.27

In [84]:
print("========== DUPLICATE ANALYSIS ==========")
duplicate_count = employee_data.duplicated().sum()
print(
    f"Number of duplicate rows: "
    f"{duplicate_count}"
)

========== DUPLICATE ANALYSIS ==========
Number of duplicate rows: 7

In [85]:
duplicate_records = employee_data[
    employee_data.duplicated(keep=False)
]

print("========== DUPLICATE RECORDS ==========")
display(duplicate_records)

========== DUPLICATE RECORDS ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [86]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for column_name in numeric_columns:
  median_value = employee_data[column_name].median()

  employee_data[column_name] = (
      employee_data[column_name].fillna(
          median_value
      )
  )

print("Numeric missing values filled using median.")

Numeric missing values filled using median.

In [87]:
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for column_name in categorical_columns:
  mode_value = employee_data[column_name].mode()[0]

  employee_data[column_name] = (
      employee_data[column_name].fillna(
          mode_value
      )
  )

print(
    "Categorical missing values filled using mode."
)

Categorical missing values filled using mode.

In [88]:
employee_data["Joining_Date"] = pd.to_datetime(
    employee_data["Joining_Date"],
    errors="coerce"
)

print("Joining_Date converted to datetime.")
print(
    employee_data["Joining_Date"].dtype
)

Joining_Date converted to datetime.
datetime64[ns]

In [89]:
missing_dates = employee_data[
    "Joining_Date"
].isnull().sum()
print(
    f"Missing or invalid joining dates: "
    f"{missing_dates}"
)

Missing or invalid joining dates: 0

In [90]:
rows_before_duplicates = len(employee_data)
employee_data = employee_data.drop_duplicates()
rows_after_duplicates = len(employee_data)
duplicates_removed = (
    rows_before_duplicates - rows_after_duplicates
)
print(
    f"Duplicate rows removed: "
    f"{duplicates_removed}"
)
print(
    f"Rows before removing duplicates: "
    f"{rows_before_duplicates}"
)
print(
    f"Rows after removing duplicates: "
    f"{rows_after_duplicates}"
)

Duplicate rows removed: 7
Rows before removing duplicates: 157
Rows after removing duplicates: 150

In [91]:
print("========== MISSING VALUES AFTER CLEANING ==========")
remaining_missing = employee_data.isnull().sum()
display(remaining_missing)

========== MISSING VALUES AFTER CLEANING ==========

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [92]:
print("========== DUPLICATES AFTER CLEANING ==========")
remaining_duplicates = (
    employee_data.duplicated().sum()
)
print(
    f"Remianing duplicate rows: "
    f"{remaining_duplicates}"
)

========== DUPLICATES AFTER CLEANING ==========
Remianing duplicate rows: 0

In [93]:
print("========== DATA TYPES AFTER CLEANING ==========")
print(employee_data.dtypes)

========== DATA TYPES AFTER CLEANING ==========
Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

In [94]:
forward_fill_demo = employee_data[
    ["Employee_ID", "Joining_Date"]
].copy()
forward_fill_demo["Joining_Date"] = (
    forward_fill_demo["Joining_Date"].ffill()
)
print(
    "Forward-fill demonstration completed."
)
display(forward_fill_demo.head())

Forward-fill demonstration completed.

  Employee_ID Joining_Date
0     EMP0098   2017-06-13
1     EMP0046   2021-09-15
2     EMP0017   2021-02-05
3     EMP0105   2018-08-05
4     EMP0143   2018-07-24

In [95]:
print("========== BEFORE VS AFTER CLEANING ==========")
print(
    f"Original number of rows: "
    f"{rows_before_duplicates}"
)
print(
    f"Final mumber of rows: "
    f"{rows_after_duplicates}"
)
print(
    f"Duplicate rows removed: "
    f"{duplicates_removed}"
)
print(
    f"Remianing duplicate rows: "
    f"{employee_data.duplicated().sum()}"
)
print(
    f"Remaining missing values: "
    f"{employee_data.isnull().sum().sum()}"
)

========== BEFORE VS AFTER CLEANING ==========
Original number of rows: 157
Final mumber of rows: 150
Duplicate rows removed: 7
Remianing duplicate rows: 0
Remaining missing values: 0

In [96]:
print("========== CLEANED DATASET STATISTICS ==========")
display(employee_data.describe())

========== CLEANED DATASET STATISTICS ==========

,Age,Annual_Salary,Experience_Years,Joining_Date,Performance_Score
count,150.000000,150.000000,150.000000,150,150.000000
mean,38.113333,88874.686667,8.919667,2021-04-06 15:12:00,3.560000
min,21.000000,43331.000000,0.600000,2017-01-04 00:00:00,2.000000
25%,31.000000,71123.500000,4.450000,2018-12-23 00:00:00,3.000000
50%,39.000000,90046.500000,9.325000,2021-01-05 00:00:00,4.000000
75%,46.000000,104693.250000,13.175000,2023-08-15 18:00:00,4.000000
max,52.000000,162942.000000,17.400000,2026-01-06 00:00:00,5.000000
std,9.245740,22355.342511,4.929877,NaN,0.923082

In [97]:
print("========== CLEANED EMPLOYEE DATASET ==========")
display(employee_data.head(10))

========== CLEANED EMPLOYEE DATASET ==========

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Marketing,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.40,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.80,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.00,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.10,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.50,2020-06-28,Chennai,4.0,Remote

In [98]:
print("========== FINAL DATASET INFORMATION ==========")
employee_data.info()

========== FINAL DATASET INFORMATION ==========
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB

In [99]:
output_file = "Day11_Cleaned_Company_Employee_Dataset.csv"
employee_data.to_csv(
    output_file,
    index=False
)
print(
    f"Cleaned dataset exported successfully as "
    f"{output_file}"
)

Cleaned dataset exported successfully as Day11_Cleaned_Company_Employee_Dataset.csv

In [100]:
print("=" * 60)
print("                   DAY 11 CLEANING SUMMARY")
print("=" * 60)
print(
    f"Original rows: {rows_before_duplicates}"
)
print(
    f"Final rows: {rows_after_duplicates}"
)
print(
    f"Duplicate rows removed: {duplicates_removed}"
)
print(
    "Numeric missing values handled using "
    "mode imputation."
)
print(
    "Joining_Date converted to datetime."
)
print(
    f"Remianing missing values: "
    f"{employee_data.isnull().sum().sum()}"
)
print(
    f"Remaing duplicate rows: "
    f"{employee_data.duplicated().sum()}"
)
print(
    f"Output file: {output_file}"
)
print("=" * 60)

============================================================
                   DAY 11 CLEANING SUMMARY
============================================================
Original rows: 157
Final rows: 150
Duplicate rows removed: 7
Numeric missing values handled using mode imputation.
Joining_Date converted to datetime.
Remianing missing values: 0
Remaing duplicate rows: 0
Output file: Day11_Cleaned_Company_Employee_Dataset.csv
============================================================